# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS Challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  target 'IOS ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOS ChallengeUITests' do
    # Pods for testing
  end

end
